language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kanwalgupta/travisapp -f Dockerfile.dev .

script:
  - docker run -e  CI=true kanwalgupta/travisapp npm run test -- --coverage